export type { inputPage as Page } from "./page";
export type { outputPage as PageProperties } from "./page";
export type { media as Media } from "./media";
export type { mediaDetail as MediaDetail } from "./media";
// export type { animeCollectionProps as AnimeCollectionProps } from "./collection";
export type { addAnimeFunction as AddAnimeFunction } from "./collection";
export type { styleDefault as StyleDefault } from "./components";
export type { buttonProps as ButtonProps } from "./components";
export type { animeListProps as AnimeListProps } from "./components";
export type { modalModel as ModalModel } from "./components";
export type { genreContainerProps as GenreContainerProps } from "./components";
